add option autosave_ignore_filetypes
Shatur/neovim-session-manager pull request #23
Opened 2022-01-15 22:22 UTC by hbiel

fixes #19

2022-01-15 22:53 UTC, Shatur requested changes
Thank you! Here is a minor suggestion:

2022-01-15 22:53 UTC, Shatur commented on lua/session_manager/utils.lua
> +function utils.is_normal_filetype(filetype)
You can replace this function with `vim.tbl_contains` call.

2022-01-16 18:33 UTC, hbiel commented on lua/session_manager/utils.lua
> +function utils.is_normal_filetype(filetype)
Thanks, I didn't know that neovim offers such functions. Those are really helpful.
I made a few more changes to make the return value more readable (at least i hope so) and to fix the linting / style errors.

I also changed the description in the readme a little bit. I think this feature works with autosave_ignore_not_normal when set to false. The buffers will still be removed before saving the session. It' just less helpful in case of 'gitcommit' as it creates an empty session.

Let me know your thoughts!

2022-01-16 19:23 UTC, Shatur requested changes
Thanks! The last suggestion:

2022-01-16 19:23 UTC, Shatur commented on lua/session_manager/utils.lua
> +  return is_normal_buftype and is_buflisted and is_normal_filetype
I would like to make it more optimal since it called in a loop. Let's evaluate conditions lazily and return `false` on first mismatch:

```suggestion
  if #vim.api.nvim_buf_get_option(buffer, 'buftype') ~= 0 then
      return false
  end
  if not vim.api.nvim_buf_get_option(buffer, 'buflisted') then
      return false
  end
  if vim.tbl_contains(config.autosave_ignore_filetypes, vim.api.nvim_buf_get_option(buffer, 'filetype')) then
      return false
  return true
```

2022-01-16 19:32 UTC, Shatur commented on README.md
> +  autosave_ignore_filetypes = { -- These filetypes will be ignored when autosaving; works best with autosave_ignore_not_normal = true
I would also slightly edit this one:
```suggestion
  autosave_ignore_not_normal = true, -- Plugin will not save a session when no buffers are opened, or all of them aren't writable or listed.
  autosave_ignore_filetypes = { -- All buffers of these file types will be closed before the session is saved.
```

2022-01-16 20:59 UTC, hbiel commented
Great suggestions - Thanks!
I've accepted them both.

2022-01-16 22:17 UTC, Shatur commented on lua/session_manager/utils.lua
> +      return false
You forgot to put end here :)

2022-01-17 06:42 UTC, hbiel commented on lua/session_manager/utils.lua
> +      return false
Oops sorry. I fixed it and also compressed it into one if-elseif-end block.

2022-01-17 07:51 UTC, merged