close unused lsp clients,  save memory
Shatur/neovim-session-manager pull request #56
Opened 2022-09-24 14:08 UTC by snowair

2022-09-24 14:10 UTC, Shatur commented
Are you trying to fix #52?
@lostl1ght, @LoneExile could you try it?

2022-09-24 14:27 UTC, lostl1ght commented
I'm currently away from my laptop. I'll test ASAP.

2022-09-24 15:43 UTC, LoneExile commented
It looks good to me. LSP and Null-ls work.

2022-09-24 16:31 UTC, lostl1ght commented
I proposed a small performance improvement. Otherwise, works like a charm.

2022-09-24 19:14 UTC, Shatur commented
Thanks, it works for me too.
I did some simplifications that should result into the same:

```lua
    -- Close unused lsp clients
    local bufs = vim.api.nvim_list_bufs()
    local lsp_clients = vim.lsp.get_active_clients()
    for _, client in pairs(lsp_clients) do
      if client.config.root_dir ~= vim.loop.cwd() then
        for _, bufnr in pairs(bufs) do
          if vim.tbl_contains(client.attached_buffers, bufnr) then
            vim.lsp.stop_client(client.id)
            break
          end
        end
      end
    end
```

@lostl1ght and @LoneExile may I ask any of you to test it again in 3 combinations:
1. Before `schedule`.
2. After schedule, but before `source`.
3. After `source`, like in this PR.

On my machine all 3 cases works. But I want to make shure it won't break anything on yours. If everything works, I would prefer to put it before schedule or at least before `source`.

2022-09-24 19:23 UTC, Shatur requested changes
Thanks! It works on my machine too.
I added a few suggestions to the algorithm. Could you apply the suggestion and move this logic into a function to the top of the file? Let's call it `stop_lsp_clients`. I think it will be better to read instead of having a comment.

2022-09-24 19:23 UTC, Shatur commented on lua/session_manager/utils.lua
> +    end
Some simplifications:
1. Use `vim.loop.cwd()` instead of `vim.fn.cwd()` because `vim.fn.*` functions are slow.
2. Use `vim.tbl_contains` instead of raw loop.
3. Added a break on first buffer match.

```suggestion
    -- Close unused lsp clients
    local bufs = vim.api.nvim_list_bufs()
    local lsp_clients = vim.lsp.get_active_clients()
    for _, client in pairs(lsp_clients) do
      if client.config.root_dir ~= vim.loop.cwd() then
        local active = false
        for _, bufnr in pairs(bufs) do
          if vim.tbl_contains(client.attached_buffers, bufnr) then
            active = true
            break
          end
        end
        if active == false then
          vim.lsp.stop_client(client.id)
        end
      end
    end
```

2022-09-24 19:24 UTC, Shatur commented
> I proposed a small performance improvement.

You probably forgot to press `Submit` because I don't see any suggestions.

2022-09-24 19:53 UTC, lostl1ght commented
> You probably forgot to press `Submit` because I don't see any suggestions.

Indeed, I had to press an additional button :)

2022-09-25 06:51 UTC, snowair commented on lua/session_manager/utils.lua
> +    end
The changes do not work correctly.

Just try:
```
:lua print ( vim.tbl_contains( {[40]=1}, 40 ) )
```

2022-09-25 06:58 UTC, snowair commented on lua/session_manager/utils.lua
> +    end
`client.attached_buffers` is not a array. Its a dict.

2022-09-25 08:37 UTC, Shatur commented on lua/session_manager/utils.lua
> +    end
Oh, right, sorry. Then instead of `if vim.tbl_contains(client.attached_buffers, bufnr) then` you could use `if client.attached_buffers[bufnr] then`?

2022-09-25 10:48 UTC, snowair commented on lua/session_manager/utils.lua
> +    end
I don't know if `client.attached_buffers` is possible like this `{ [40] = false, [41]=true }`

2022-09-25 10:51 UTC, Shatur commented on lua/session_manager/utils.lua
> +    end
Oh, okay, makes sense. Let's use `if client.attached_buffers[bufnr] ~= then` just to be sure.

2022-09-25 11:14 UTC, snowair commented on lua/session_manager/utils.lua
> +    end
Well, perfect change！

2022-09-25 12:42 UTC, Shatur commented
@snowair Could you fix formatting issues and move this logic into a local function as I suggested? I can't push changed into your branch because your created it on your `master`.

2022-09-25 16:03 UTC, merged