Do not shorten the path completely
Shatur/neovim-session-manager pull request #57
Opened 2022-09-28 00:50 UTC by knmac

The old shorten_path function will completely reduce the path as soon as it exceeds config.max_path_length, e.g., `/dir1/dir2/dir3/dir4/dir5/dir6/filename` will become `/d/d/d/d/d/d/filename`, which may be too short. The new implementation ensures that the tailing directories are excluded, as long as the shortened path does not exceed the limit, e.g., `/d/d/d/d/dir5/dir6/filename`.

2022-09-28 07:16 UTC, Shatur requested changes

2022-09-28 07:16 UTC, Shatur commented on lua/session_manager/utils.lua
> +    while string.len(Path:new(filename):shorten(1, excludes)) < config.max_path_length do
Let's cache `Path:new(filename):shorten(1, excludes)` before the loop to avoid calculating it twice.

2022-09-28 07:16 UTC, Shatur commented on lua/session_manager/utils.lua
> +    local excludes = { -1 }  -- index to exclude from shortening, -1 means last
```suggestion
    local excludes = { -1 }  -- Index to exclude from shortening, -1 means last
```

2022-09-28 07:16 UTC, Shatur commented on lua/session_manager/utils.lua
> +    local shortened = nil
Maybe assign it to `filename`?

2022-09-28 16:48 UTC, knmac commented on lua/session_manager/utils.lua
> +    local shortened = nil
Can you please clarify?

2022-09-28 17:42 UTC, Shatur requested changes

2022-09-28 17:42 UTC, Shatur commented on lua/session_manager/utils.lua
> +    return shortened
Will something like this work? Can't test currently, but the idea is to avoid creating a new Plenary.Path every time and just reuse the previous one.
```suggestion
    local shortened = Path:new(filename):shorten(1, excludes)

    -- Gradually increase the tailing excludes
    while #shortened.filename < config.max_path_length do
      -- Try to short more with more excludes
      excludes[#excludes + 1] = excludes[#excludes] - 1
      shortened = shortened:shorten(1, excludes)
    end
    return shortened.filename
```

2022-09-28 17:42 UTC, Shatur commented on lua/session_manager/utils.lua
> +    local shortened = nil
Never mind, you basically did what I suggested in the last commit.

2022-09-28 18:13 UTC, knmac commented on lua/session_manager/utils.lua
> +    return shortened
If I understand correctly, it doesn't seem to work unless we reimplement the functions from plenary.path.

An example for this is `/dir1/dir2/dir3/filename.ext` becomes `/d/d/d/filename.ext` with `excludes = {  -1  }`. With the 2nd iteration where `excludes = { -1, -2 }`, `/d/d/d/filename.ext` is still `/d/d/d/filename.ext` because the text `dir3` is already shortened as `d`.

Please feel free to correct me as I'm not fluent in lua.

2022-09-29 08:45 UTC, Shatur commented on lua/session_manager/utils.lua
> +    return shortened
You are right! I get it wrong for the first time.

2022-09-29 08:45 UTC, merged